import type { LessonProps } from '../../App'
import { LessonLayout } from '../../components/lesson/LessonLayout'
import {
  LessonSection, P, Strong, Callout, StepFlow,
  KeyTermsGrid, ConfusionBlock, RecallBlock, CheatSheet,
} from '../../components/lesson/blocks'
import { Quiz } from '../../components/lesson/Quiz'
import { InteractiveFlowMap, TabbedContent, ExpandableCardGrid } from '../../components/ui'

export default function CompanyAnalysis({ onNavigate }: LessonProps) {
  return (
    <LessonLayout
      moduleId="m3"
      lessonId="company-analysis"
      subtitle="A stock is a slice of a business. Learn to read the three financial statements, spot real quality, and see why a great product is not the same thing as a great investment."
      onNavigate={onNavigate}
    >
      <LessonSection title="Think like an owner, not a customer" icon="🧠">
        <P>
          A consumer asks <Strong>"do I like this product?"</Strong> An investor asks a harder question:{' '}
          <Strong>"is this a good business, and is it priced fairly?"</Strong> Many beloved companies are terrible
          investments, and many boring ones quietly compound for decades.
        </P>
        <P>
          Business analysis isn't accounting. It's knowing enough to judge whether a company{' '}
          <Strong>deserves your capital</Strong> — can it sustain and grow profits, and what could break that?
        </P>
      </LessonSection>

      <LessonSection title="How a business makes money" icon="💰">
        <P>
          Every business is the same machine: money in, costs out, and a decision about what to do with what's left.
          Tap each stage — the interesting part is how <Strong>profit</Strong> and <Strong>cash flow</Strong> can
          tell different stories.
        </P>
        <InteractiveFlowMap
          nodes={[
            { id: 'revenue', label: 'Revenue', description: 'Total money coming in from selling products or services — the "top line" of the income statement. More revenue doesn\'t automatically mean success; what matters is how much survives the costs below it.', color: 'green' },
            { id: 'costs', label: 'Costs', description: 'Everything it takes to run the business — materials, salaries, rent, marketing, R&D, interest on debt. The unit economics question: what does one sale earn after its direct costs? Companies with lower costs relative to revenue have better margins.', color: 'red' },
            { id: 'profit', label: 'Profit', description: 'Revenue minus costs — "net income," the bottom line. What the business earned for its owners on paper. But profit can be shaped by accounting choices, so always check cash flow too.', color: 'blue' },
            { id: 'cashflow', label: 'Cash Flow', description: 'Actual cash generated by operations — harder to manipulate than profit. Free cash flow (FCF) = operating cash flow minus capital expenditures. This is the real money available for shareholders.', color: 'purple' },
            { id: 'reinvest', label: 'Reinvest or Return', description: 'The business either reinvests profit into growth (R&D, expansion, acquisitions) or returns it to shareholders (dividends, buybacks). Great businesses do both wisely — bad ones burn it on empire-building.', color: 'indigo' },
          ]}
        />
      </LessonSection>

      <LessonSection title="The three financial statements" icon="📑">
        <P>
          Three documents describe every public company. Each answers a different question — and each can be checked
          against the others.
        </P>
        <TabbedContent tabs={[
          {
            label: 'Income Statement',
            content: (
              <div className="space-y-3 text-sm text-slate-600 dark:text-slate-400">
                <p><strong className="text-slate-800 dark:text-slate-200">The performance report:</strong> what the company earned and spent over a period (a quarter or a year).</p>
                <div className="p-4 bg-slate-50 dark:bg-slate-800/60 rounded-xl border border-slate-200 dark:border-slate-700 space-y-2">
                  <div className="flex justify-between gap-3"><span>Revenue (sales)</span><span className="font-mono text-emerald-700 dark:text-emerald-400">$100M</span></div>
                  <div className="flex justify-between gap-3"><span>– Cost of Goods Sold</span><span className="font-mono text-rose-600 dark:text-rose-400">−$40M</span></div>
                  <div className="flex justify-between gap-3 font-medium border-t border-slate-200 dark:border-slate-700 pt-1"><span>= Gross Profit</span><span className="font-mono">$60M</span></div>
                  <div className="flex justify-between gap-3"><span>– Operating Expenses</span><span className="font-mono text-rose-600 dark:text-rose-400">−$30M</span></div>
                  <div className="flex justify-between gap-3 font-medium border-t border-slate-200 dark:border-slate-700 pt-1"><span>= Operating Profit (EBIT)</span><span className="font-mono">$30M</span></div>
                  <div className="flex justify-between gap-3"><span>– Interest & Taxes</span><span className="font-mono text-rose-600 dark:text-rose-400">−$8M</span></div>
                  <div className="flex justify-between gap-3 font-bold border-t border-slate-200 dark:border-slate-700 pt-1"><span>= Net Income</span><span className="font-mono text-emerald-700 dark:text-emerald-400">$22M</span></div>
                </div>
                <p><strong className="text-slate-800 dark:text-slate-200">Key margins:</strong> gross margin (60% here), operating margin (30%), net margin (22%). Persistently high margins usually signal a competitive advantage — compare within an industry, not across.</p>
              </div>
            ),
          },
          {
            label: 'Balance Sheet',
            content: (
              <div className="space-y-3 text-sm text-slate-600 dark:text-slate-400">
                <p><strong className="text-slate-800 dark:text-slate-200">The snapshot:</strong> what the company owns (assets) and owes (liabilities) at one moment. The difference is shareholder equity — the book value of the business.</p>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                  <div className="p-4 bg-emerald-50 dark:bg-emerald-950/40 rounded-xl border border-emerald-200 dark:border-emerald-800">
                    <h5 className="font-semibold text-emerald-800 dark:text-emerald-300 mb-2">Assets (what they own)</h5>
                    <ul className="space-y-1 text-emerald-700 dark:text-emerald-300/90 text-sm">
                      <li>Cash & equivalents: $30M</li>
                      <li>Inventory: $15M</li>
                      <li>Property & equipment: $50M</li>
                      <li>Intangible assets: $25M</li>
                      <li className="font-bold border-t border-emerald-200 dark:border-emerald-800 pt-1">Total Assets: $120M</li>
                    </ul>
                  </div>
                  <div className="p-4 bg-rose-50 dark:bg-rose-950/40 rounded-xl border border-rose-200 dark:border-rose-800">
                    <h5 className="font-semibold text-rose-800 dark:text-rose-300 mb-2">Liabilities + Equity</h5>
                    <ul className="space-y-1 text-rose-700 dark:text-rose-300/90 text-sm">
                      <li>Short-term debt: $10M</li>
                      <li>Long-term debt: $35M</li>
                      <li>Accounts payable: $5M</li>
                      <li className="border-t border-rose-200 dark:border-rose-800 pt-1">Total Liabilities: $50M</li>
                      <li className="font-bold text-indigo-700 dark:text-indigo-300 border-t border-rose-200 dark:border-rose-800 pt-1">Shareholder Equity: $70M</li>
                    </ul>
                  </div>
                </div>
                <p><strong className="text-slate-800 dark:text-slate-200">Key identity:</strong> Assets = Liabilities + Equity, always. High debt relative to equity means higher financial risk when the cycle turns.</p>
              </div>
            ),
          },
          {
            label: 'Cash Flow Statement',
            content: (
              <div className="space-y-3 text-sm text-slate-600 dark:text-slate-400">
                <p><strong className="text-slate-800 dark:text-slate-200">The lie detector:</strong> where cash actually came from and went. Cash is far harder to fake than accounting profit.</p>
                <div className="p-4 bg-slate-50 dark:bg-slate-800/60 rounded-xl border border-slate-200 dark:border-slate-700 space-y-2">
                  <div className="flex justify-between gap-3"><span>Operating Cash Flow</span><span className="font-mono text-emerald-700 dark:text-emerald-400">$28M</span></div>
                  <div className="flex justify-between gap-3"><span>– Capital Expenditures</span><span className="font-mono text-rose-600 dark:text-rose-400">−$10M</span></div>
                  <div className="flex justify-between gap-3 font-bold border-t border-slate-200 dark:border-slate-700 pt-1"><span>= Free Cash Flow (FCF)</span><span className="font-mono text-emerald-700 dark:text-emerald-400">$18M</span></div>
                </div>
                <p><strong className="text-slate-800 dark:text-slate-200">Why FCF matters:</strong> it's the money left after maintaining the business — available for dividends, buybacks, debt paydown, or growth. If net income is high but FCF is persistently low, something is off.</p>
              </div>
            ),
          },
        ]} />
      </LessonSection>

      <LessonSection title="How the statements connect" icon="🔗">
        <P>
          The three statements aren't separate documents — they're <Strong>one system viewed from three angles</Strong>,
          and each one checks the others:
        </P>
        <StepFlow
          steps={[
            { label: 'The income statement books the period\'s profit', detail: 'Revenue minus all costs ends at net income — the bottom line for the quarter or year.' },
            { label: 'Net income flows into the balance sheet', detail: 'Profit that isn\'t paid out as dividends becomes retained earnings, growing shareholder equity.' },
            { label: 'The cash flow statement reconciles profit to cash', detail: 'It starts from net income and adjusts for non-cash items (depreciation) and working capital to show real cash movement.' },
            { label: 'Ending cash lands back on the balance sheet', detail: 'The closing cash on the cash flow statement is exactly the cash line on the next balance sheet. The loop closes.' },
          ]}
        />
        <Callout type="tip" title="The one thing to remember">
          Profit is an opinion; cash is a fact. When reported earnings and free cash flow tell the same story for
          years, trust the business. When they diverge, trust the cash — and dig into why.
        </Callout>
      </LessonSection>

      <LessonSection title="Quality signals and red flags" icon="🔍">
        <P>
          Six things investors typically check before anything else. Expand each card — the details include the red
          flags as well as the green ones.
        </P>
        <ExpandableCardGrid columns={2} cards={[
          {
            title: 'Revenue Growth',
            content: 'Is the company selling more over time? Consistent growth suggests real demand and market expansion.',
            details: 'Look for steady, sustainable growth rather than one-time spikes. 10–20% annual growth for a mature company is strong; hypergrowth (50%+) is exciting but rarely sustainable. Declining revenue is a red flag unless the company is deliberately restructuring.',
            color: 'green',
          },
          {
            title: 'Profit Margins',
            content: 'How much of each dollar of revenue becomes profit? High, stable margins often indicate competitive advantage.',
            details: 'Gross margin: revenue after direct costs. Operating margin: after operating expenses. Net margin: after everything. Software companies can run 70%+ gross margins; retailers might run 25%. Compare within industries, never across them.',
            color: 'blue',
          },
          {
            title: 'Debt Levels',
            content: 'How much does the company owe relative to what it earns? Debt amplifies both gains and losses.',
            details: 'Debt-to-equity measures leverage. Some debt is healthy — cheap financing for growth. Too much becomes dangerous in recessions, when revenue drops but interest payments stay fixed. Low debt plus high cash reserves = resilience.',
            color: 'orange',
          },
          {
            title: 'Free Cash Flow',
            content: 'The real cash generated after maintaining the business. More trustworthy than reported profits.',
            details: 'A company can report profits while burning cash — through aggressive revenue recognition, inventory buildup, or accounting choices. Consistently positive and growing FCF is the single best indicator of business health.',
            color: 'purple',
          },
          {
            title: 'Competitive Advantage (Moat)',
            content: 'What stops competitors from copying this business? Moats protect long-term profitability.',
            details: 'Types of moats: brand power (Apple), network effects (Visa), switching costs (Microsoft), cost advantage (Walmart), regulatory barriers (utilities). Businesses without moats eventually see their margins competed away. This is the most important qualitative factor.',
            color: 'indigo',
          },
          {
            title: 'Management Quality',
            content: 'Are the people running the company competent, honest, and aligned with shareholders?',
            details: 'Green flags: insider ownership, consistent capital allocation, transparent communication, reasonable pay, long tenure. Red flags: frequent overpriced acquisitions, empire-building, and heavy stock compensation that dilutes shareholders.',
            color: 'teal',
          },
        ]} />
      </LessonSection>

      <LessonSection title="Common confusion" icon="🌀">
        <ConfusionBlock
          items={[
            {
              a: 'Revenue',
              b: 'Profit',
              explanation:
                'Revenue is total sales; profit is what remains after all costs. A company can book $1B in revenue and earn nothing if costs eat it all. Revenue alone tells you nothing about profitability.',
            },
            {
              a: 'Profit',
              b: 'Cash flow',
              explanation:
                'Accounting profit can be shaped by depreciation schedules, accruals, and revenue-recognition choices. Cash flow shows actual money in and out. A company can look "profitable" on paper while running out of cash.',
            },
            {
              a: 'A good product',
              b: 'A good investment',
              explanation:
                'You might love a company\'s product, but the business behind it may have thin margins, heavy debt, or an overpriced stock. Investment quality depends on fundamentals AND price — the next lesson covers the price half.',
            },
          ]}
        />
      </LessonSection>

      <LessonSection title="Key terms" icon="🔑">
        <KeyTermsGrid
          terms={[
            { term: 'Revenue', definition: 'Total sales — the "top line" of the income statement. The starting point, not the verdict.' },
            { term: 'Net income', definition: 'Profit after all expenses, interest, and taxes. The "bottom line" — useful, but shaped by accounting choices.' },
            { term: 'Free cash flow (FCF)', definition: 'Operating cash flow minus capital expenditures. The real cash a business generates for its owners.' },
            { term: 'Gross margin', definition: 'Revenue minus cost of goods sold, divided by revenue. The core unit-economics number — what one sale earns after direct costs.' },
            { term: 'Debt-to-equity', definition: 'Total debt divided by shareholder equity. Higher ratio = more leverage, more fragility in downturns.' },
            { term: 'Moat', definition: 'A durable competitive advantage — brand, network effects, switching costs — that protects margins from competitors over time.' },
          ]}
        />
      </LessonSection>

      <LessonSection title="Check your understanding" icon="✅">
        <Quiz
          questions={[
            {
              question: 'A company reports $1B in revenue. What do you know about its profitability?',
              options: [
                'It\'s highly profitable — $1B is a lot of money',
                'Almost nothing — profitability depends on what\'s left after all costs',
                'It must be at least 10% profitable, the market average',
                'It\'s unprofitable — big-revenue companies usually run at a loss',
              ],
              correct: 1,
              explanation:
                'Revenue is the top line, not the verdict. A $1B-revenue company with $1B in costs earns nothing. Margins — how much of each dollar survives the trip down the income statement — are what turn revenue into value.',
            },
            {
              question: 'Net income has been strong for three years, but free cash flow is persistently near zero. What\'s the most reasonable read?',
              options: [
                'Great — profits are what count, cash flow is a technicality',
                'The company is definitely committing fraud',
                'Earnings may be driven by accounting rather than cash — dig into why they diverge',
                'FCF doesn\'t matter for profitable companies',
              ],
              correct: 2,
              explanation:
                'Profit is an opinion, cash is a fact. Persistent divergence isn\'t proof of fraud, but it is a signal: aggressive revenue recognition, ballooning inventory, or heavy capex can all make paper profits that never become spendable cash.',
            },
            {
              question: 'Why does a moat matter more than this quarter\'s growth rate?',
              options: [
                'Because moats guarantee the stock price will rise',
                'Because growth is impossible without a moat',
                'Because moats make a company immune to recessions',
                'Because without a moat, competitors eventually compete the margins away — growth without protection fades',
              ],
              correct: 3,
              explanation:
                'High margins attract competition. A moat — brand, network effects, switching costs, cost advantage — is what lets a business defend those margins for years. Growth without a moat tends to be rented, not owned.',
            },
          ]}
        />
      </LessonSection>

      <LessonSection title="Recall — answer before revealing" icon="🧠">
        <RecallBlock
          prompts={[
            { question: 'What are the three main financial statements, and what does each answer?', answer: 'Income statement: what the company earned and spent over a period. Balance sheet: what it owns and owes at a moment in time. Cash flow statement: where cash actually came from and went. Together they form one self-checking system.' },
            { question: 'Why is free cash flow often more reliable than net income?', answer: 'Cash is harder to manipulate than accounting profit. Net income can be inflated through aggressive accounting; FCF shows the actual cash generated after maintaining the business. When they persistently diverge, trust the cash and investigate.' },
            { question: 'What is a competitive moat and why does it matter?', answer: 'A durable advantage — brand, network effects, switching costs, cost advantage, regulation — that protects a business from competitors. Without one, high margins get competed away. Moats are what allow companies to stay very profitable for many years.' },
          ]}
        />
      </LessonSection>

      <CheatSheet
        items={[
          { label: 'Revenue', value: 'Total sales — the starting point, never the verdict.' },
          { label: 'Profit', value: 'What\'s left after all costs. An opinion shaped by accounting.' },
          { label: 'FCF', value: 'Real cash generated. Trust this over reported profit.' },
          { label: 'Margins', value: 'Higher and stabler = usually better. Compare within an industry.' },
          { label: 'Debt', value: 'Some is fine. Too much = fragile when the cycle turns.' },
          { label: 'Moat', value: 'The advantage that keeps margins from being competed away.' },
        ]}
      />
    </LessonLayout>
  )
}
