import {
  SectionShell, SectionHeader, Subsection, Prose, InteractiveFlowMap,
  ExpandableCardGrid, CompareTable, TermsMemoryBlock, CommonConfusionBlock,
  MiniRecallBlock, CheatSheetPanel, InfoCallout, TabbedContent
} from '../components/ui'

export default function Section08() {
  return (
    <SectionShell id="section-8">
      <SectionHeader
        number={8}
        title="How to Think About a Business as an Investor"
        subtitle="A good product does not always mean a good investment. Understanding business fundamentals helps you evaluate what you're actually buying."
      />

      <Subsection title="Investor Thinking vs. Consumer Thinking">
        <Prose>
          <p>As a consumer, you ask: "Do I like this product?" As an investor, you ask: "Is this a good business? Is it priced fairly? Can it sustain and grow profits?" These are very different questions. Many beloved companies are terrible investments, and many boring companies are excellent ones.</p>
          <p>Understanding basic business analysis is not about becoming an accountant. It's about knowing enough to evaluate whether a business deserves your capital and at what price.</p>
        </Prose>
      </Subsection>

      <Subsection title="How a Business Makes Money">
        <InteractiveFlowMap
          nodes={[
            { id: 'revenue', label: 'Revenue', description: 'Total money coming in from selling products or services. Also called "top line" because it\'s the first line of the income statement. More revenue doesn\'t automatically mean success — what matters is how much is left after costs.', color: 'green' },
            { id: 'costs', label: 'Costs', description: 'Everything it takes to run the business — raw materials, salaries, rent, marketing, R&D, interest on debt. Costs eat into revenue. Companies with lower costs relative to revenue have better margins.', color: 'red' },
            { id: 'profit', label: 'Profit', description: 'Revenue minus costs. Also called "net income" or "bottom line." This is what the business actually earned for its owners (shareholders). But profit can be manipulated through accounting — always check cash flow too.', color: 'blue' },
            { id: 'cashflow', label: 'Cash Flow', description: 'Actual cash generated by operations. More reliable than profit because it\'s harder to manipulate. Free cash flow (FCF) = operating cash flow minus capital expenditures. This is the real money available for shareholders.', color: 'purple' },
            { id: 'reinvest', label: 'Reinvest or Return', description: 'The business either reinvests profit back into growth (R&D, expansion, acquisitions) or returns it to shareholders (dividends, buybacks). Great businesses do both wisely.', color: 'indigo' },
          ]}
        />
      </Subsection>

      <Subsection title="The Three Financial Statements">
        <TabbedContent tabs={[
          {
            label: 'Income Statement',
            content: (
              <div className="space-y-3 text-sm text-slate-600">
                <p><strong className="text-slate-800">What it tells you:</strong> How much the company earned and spent over a period (quarterly or annually). Think of it as the "performance report."</p>
                <div className="p-4 bg-slate-50 rounded-xl border border-slate-200 space-y-2">
                  <div className="flex justify-between"><span>Revenue (sales)</span><span className="font-mono text-emerald-700">$100M</span></div>
                  <div className="flex justify-between"><span>– Cost of Goods Sold</span><span className="font-mono text-red-600">−$40M</span></div>
                  <div className="flex justify-between font-medium border-t pt-1"><span>= Gross Profit</span><span className="font-mono">$60M</span></div>
                  <div className="flex justify-between"><span>– Operating Expenses</span><span className="font-mono text-red-600">−$30M</span></div>
                  <div className="flex justify-between font-medium border-t pt-1"><span>= Operating Profit (EBIT)</span><span className="font-mono">$30M</span></div>
                  <div className="flex justify-between"><span>– Interest & Taxes</span><span className="font-mono text-red-600">−$8M</span></div>
                  <div className="flex justify-between font-bold border-t pt-1"><span>= Net Income</span><span className="font-mono text-emerald-700">$22M</span></div>
                </div>
                <p><strong className="text-slate-800">Key margins:</strong> Gross margin (60% above), Operating margin (30%), Net margin (22%). Higher margins usually mean competitive advantages.</p>
              </div>
            ),
          },
          {
            label: 'Balance Sheet',
            content: (
              <div className="space-y-3 text-sm text-slate-600">
                <p><strong className="text-slate-800">What it tells you:</strong> What the company owns (assets) and owes (liabilities) at a specific moment. The difference is shareholder equity — the book value of the business.</p>
                <div className="grid md:grid-cols-2 gap-4">
                  <div className="p-4 bg-emerald-50 rounded-xl border border-emerald-200">
                    <h5 className="font-semibold text-emerald-800 mb-2">Assets (what they own)</h5>
                    <ul className="space-y-1 text-emerald-700 text-sm">
                      <li>Cash & equivalents: $30M</li>
                      <li>Inventory: $15M</li>
                      <li>Property & equipment: $50M</li>
                      <li>Intangible assets: $25M</li>
                      <li className="font-bold border-t pt-1">Total Assets: $120M</li>
                    </ul>
                  </div>
                  <div className="p-4 bg-rose-50 rounded-xl border border-rose-200">
                    <h5 className="font-semibold text-rose-800 mb-2">Liabilities + Equity</h5>
                    <ul className="space-y-1 text-rose-700 text-sm">
                      <li>Short-term debt: $10M</li>
                      <li>Long-term debt: $35M</li>
                      <li>Accounts payable: $5M</li>
                      <li className="border-t pt-1">Total Liabilities: $50M</li>
                      <li className="font-bold text-indigo-700 border-t pt-1">Shareholder Equity: $70M</li>
                    </ul>
                  </div>
                </div>
                <p><strong className="text-slate-800">Key identity:</strong> Assets = Liabilities + Equity. Always true. High debt relative to equity = higher financial risk.</p>
              </div>
            ),
          },
          {
            label: 'Cash Flow Statement',
            content: (
              <div className="space-y-3 text-sm text-slate-600">
                <p><strong className="text-slate-800">What it tells you:</strong> Where cash actually came from and went. More reliable than the income statement because cash is harder to fake than accounting profits.</p>
                <div className="p-4 bg-slate-50 rounded-xl border border-slate-200 space-y-2">
                  <div className="flex justify-between"><span>Operating Cash Flow</span><span className="font-mono text-emerald-700">$28M</span></div>
                  <div className="flex justify-between"><span>– Capital Expenditures</span><span className="font-mono text-red-600">−$10M</span></div>
                  <div className="flex justify-between font-bold border-t pt-1"><span>= Free Cash Flow (FCF)</span><span className="font-mono text-emerald-700">$18M</span></div>
                </div>
                <p><strong className="text-slate-800">Why FCF matters:</strong> Free cash flow is the actual money available after maintaining the business. It's what can be used for dividends, buybacks, debt repayment, or growth. If net income is high but FCF is low, something is off.</p>
              </div>
            ),
          },
        ]} />
      </Subsection>

      <Subsection title="Key Business Quality Indicators">
        <ExpandableCardGrid columns={2} cards={[
          {
            title: 'Revenue Growth',
            content: 'Is the company selling more over time? Consistent revenue growth suggests demand for its products and market expansion.',
            details: 'Look for steady, sustainable growth rather than one-time spikes. 10-20% annual revenue growth for a mature company is strong. Hypergrowth (50%+) is exciting but often unsustainable. Declining revenue is a red flag unless the company is intentionally restructuring.',
            color: 'green',
          },
          {
            title: 'Profit Margins',
            content: 'How much of each dollar of revenue becomes profit? Higher margins often indicate competitive advantages.',
            details: 'Gross margin: revenue after direct costs. Operating margin: after operating expenses. Net margin: after everything. Software companies might have 70%+ gross margins. Retailers might have 25%. Compare within industries, not across them.',
            color: 'blue',
          },
          {
            title: 'Debt Levels',
            content: 'How much does the company owe relative to what it earns? Debt amplifies both gains and losses.',
            details: 'Debt-to-equity ratio measures financial leverage. Some debt is healthy (cheap financing for growth). Too much debt becomes dangerous in recessions when revenue drops but interest payments remain fixed. Companies with low debt and high cash reserves are more resilient.',
            color: 'orange',
          },
          {
            title: 'Free Cash Flow',
            content: 'The real cash generated after maintaining the business. More trustworthy than reported profits.',
            details: 'A company can report profits while actually burning cash (through accounting tricks, inventory buildup, aggressive recognition). FCF reveals the truth. Consistently positive and growing FCF is the best indicator of business health.',
            color: 'purple',
          },
          {
            title: 'Competitive Advantage (Moat)',
            content: 'What stops competitors from copying this business? Moats protect long-term profitability.',
            details: 'Types of moats: brand power (Apple), network effects (Visa), switching costs (Microsoft), cost advantage (Walmart), regulatory barriers (utilities). Businesses without moats eventually see their margins competed away. Moats are the most important qualitative factor.',
            color: 'indigo',
          },
          {
            title: 'Management Quality',
            content: 'Are the people running the company competent, honest, and aligned with shareholders?',
            details: 'Look for: insider ownership (skin in the game), consistent capital allocation, transparent communication, reasonable compensation, long tenure. Red flags: frequent acquisitions at high prices, empire-building, excessive stock compensation diluting shareholders.',
            color: 'teal',
          },
        ]} />
      </Subsection>

      <Subsection title="Key Terms to Remember">
        <TermsMemoryBlock terms={[
          { term: 'Revenue', definition: 'Total sales. The "top line" of the income statement.' },
          { term: 'Net Income', definition: 'Profit after all expenses, interest, and taxes. The "bottom line."' },
          { term: 'Free Cash Flow (FCF)', definition: 'Operating cash flow minus capital expenditures. The real cash a business generates for its owners.' },
          { term: 'Gross Margin', definition: 'Revenue minus cost of goods sold, divided by revenue. Measures production efficiency.' },
          { term: 'Operating Margin', definition: 'Operating profit / revenue. Shows how efficiently the core business runs.' },
          { term: 'Debt-to-Equity', definition: 'Total debt / shareholder equity. Higher ratio = more financial leverage and risk.' },
          { term: 'Moat', definition: 'Sustainable competitive advantage that protects a business from competitors over time.' },
          { term: 'Capital Expenditure (CapEx)', definition: 'Money spent to maintain or expand physical assets (factories, equipment, infrastructure).' },
        ]} />
      </Subsection>

      <Subsection title="Common Confusion">
        <CommonConfusionBlock confusions={[
          { itemA: 'Revenue', itemB: 'Profit', explanation: 'Revenue is total sales. Profit is what remains after all costs. A company can have $1B in revenue and zero profit if costs equal revenue. Revenue alone tells you nothing about profitability.' },
          { itemA: 'Profit', itemB: 'Cash flow', explanation: 'Accounting profit can be manipulated through depreciation, accruals, and revenue recognition. Cash flow shows actual money in and out. A company can be "profitable" on paper while running out of cash.' },
          { itemA: 'A good product', itemB: 'A good investment', explanation: 'You might love using a company\'s product, but that doesn\'t mean the stock is a good buy. The business might have thin margins, heavy debt, or an overvalued stock price. Investment quality depends on fundamentals AND price.' },
        ]} />
      </Subsection>

      <Subsection title="Mini Recall">
        <MiniRecallBlock questions={[
          { question: 'What are the three main financial statements?', answer: 'Income Statement (what the company earned and spent), Balance Sheet (what it owns and owes), Cash Flow Statement (where cash actually came from and went). Together they give a complete picture of business health.' },
          { question: 'Why is Free Cash Flow (FCF) often more reliable than net income?', answer: 'Because cash is harder to manipulate than accounting profits. Net income can be inflated through aggressive accounting, but FCF shows actual cash generated. If FCF consistently diverges from net income, dig deeper.' },
          { question: 'What is a competitive moat and why does it matter?', answer: 'A moat is a sustainable advantage that protects a business from competitors (brand, network effects, switching costs, etc.). Without a moat, competitors will eventually erode profits. Moats are what allow companies to maintain high margins over many years.' },
        ]} />
      </Subsection>

      <Subsection title="Section Summary">
        <CheatSheetPanel items={[
          { label: 'Revenue', value: 'Total sales — the starting point' },
          { label: 'Profit', value: 'What\'s left after all costs' },
          { label: 'FCF', value: 'Real cash generated — trust this over reported profit' },
          { label: 'Margins', value: 'Higher = usually better. Compare within industry.' },
          { label: 'Debt', value: 'Some is ok. Too much = fragile in downturns.' },
          { label: 'Moat', value: 'The competitive advantage that sustains profits' },
          { label: 'Key Insight', value: 'Good product ≠ good investment. Fundamentals + price both matter.' },
        ]} />
      </Subsection>
    </SectionShell>
  )
}
